# Generated by Django 4.0.3 on 2023-05-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estores', '0013_coupon_item_image_order_being_delivered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(default='Ogun', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='options',
            field=models.CharField(max_length=1),
        ),
    ]
