# Generated by Django 4.0.3 on 2023-05-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estores', '0014_address_state_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='options',
            field=models.CharField(max_length=10),
        ),
    ]
