# Generated by Django 4.0.3 on 2023-07-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estores', '0018_item_image1_item_image2_item_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review_rating',
            field=models.CharField(choices=[('20%', '1'), ('40%', '2'), ('60%', '3'), ('80%', '4'), ('100%', '5')], max_length=10),
        ),
    ]
