# Generated by Django 4.0.3 on 2023-07-12 14:11

import django.core.validators
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('estores', '0021_budgets_delete_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_value',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Coupon Quantity'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(check=models.Q(('used__lte', django.db.models.expressions.F('max_value'))), name='constrain-max-limit'),
        ),
    ]
