# Generated by Django 4.0.3 on 2023-07-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estores', '0024_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(editable=False),
        ),
    ]
