# Generated by Django 4.0.3 on 2023-07-20 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estores', '0025_alter_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image1',
            field=models.ImageField(default='product-3-2.jpg', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='image2',
            field=models.ImageField(default='product-3-2.jpg', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='image3',
            field=models.ImageField(default='product-3-2.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
